### ISSUE TITLE
KeyError: 'currentTime2'

### ISSUE THREAD

**Issue by AwfulJamBalaYa** [FanbeiFan/JD-SHOPPER#2]
请选择:1
Traceback (most recent call last):
  File "F:\JD-SHOPPER-1.1.1\main.py", line 19, in <module>
    waiter = Waiter()
  File "F:\JD-SHOPPER-1.1.1\Core\spider.py", line 59, in __init__
    self.timers = Timer(self.buyTime)
  File "F:\JD-SHOPPER-1.1.1\Core\timer.py", line 25, in __init__
    self.diff_time = self.local_jd_time_diff()
  File "F:\JD-SHOPPER-1.1.1\Core\timer.py", line 50, in local_jd_time_diff
    return self.local_time() - self.jd_time()
  File "F:\JD-SHOPPER-1.1.1\Core\timer.py", line 35, in jd_time
    return int(js["currentTime2"])
KeyError: 'currentTime2'

**Comment by AwfulJamBalaYa** [comment]
Cores/timer.py 对应位置修改为读取本地时间

**Comment by Kiocol** [comment]
大神能具体说下代码咋改吗
